In [1]:
import numpy as np

In [2]:
# indexing and slicing in numpy arrays

In [3]:
# indexing = accessing individual elements of an array
# slicing = accessing a range of elements in an array

In [7]:
# indexing in 1d array
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arr1)

[ 10  20  30  40  50  60  70  80  90 100]


In [8]:
arr1[-1]

np.int64(100)

In [10]:
# indexing in 2d array
arr2 = np.random.randint(low=1, high=20, size=(4, 4))
print(arr2)

[[ 9  2 14 14]
 [ 9  7  3 16]
 [ 4  7 13  8]
 [ 4  4  2  3]]


In [11]:
arr2[1,1] #arr[row position, column position    ]

np.int32(7)

In [12]:
arr2[3,3]

np.int32(3)

In [13]:
# slicing in 1d array
arrs = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arrs)

[ 10  20  30  40  50  60  70  80  90 100]


In [16]:
# syntax : arr[start : end : step]
arrs[0:2]  # from index 2 to index 7 , step 2

array([10, 20])

In [17]:
arrs[::2]

array([10, 30, 50, 70, 90])

In [18]:
arrs[0:-1:2]

array([10, 30, 50, 70, 90])

In [19]:
# slicing in 2d array
arrs2d = np.random.randint(1,50,(5,5))
print(arrs2d)

[[39 42  2 45 22]
 [23 16 33 37 36]
 [47 16 48 15 30]
 [25  3 22 48 49]
 [46  9 43 41 43]]


In [23]:
print(arrs2d[2:4,2:4]) # syntax arr[row, column]

[[48 15]
 [22 48]]


In [24]:
print(arrs2d[2:4,2:-1]) # syntax arr[row, column]

[[48 15]
 [22 48]]


In [27]:
print(arrs2d[3::,3::])

[[48 49]
 [41 43]]


In [28]:
print(arrs2d[3:5,3:5])

[[48 49]
 [41 43]]


In [36]:
arr3d = np.random.randint(1,100,(3,6,6)) # 3d array with 3 matrices of 6x6
print(arr3d)

[[[25  8 53 68 30 86]
  [94 78 84 75 96  8]
  [65 53 38 60 64 48]
  [88 45 69 87 89 70]
  [84 49 50 18 62 20]
  [ 9 45 94 11 65 54]]

 [[80 31 94 94 55 10]
  [88 22 23 30 63 38]
  [ 8 11 47  6  1 25]
  [49 58  2 68 60 51]
  [ 5 36 65 11 88 89]
  [ 3  9 98  3 49 96]]

 [[ 3 37  4 70 27 57]
  [31 86 73 88 27 97]
  [10 62 60 86 86 76]
  [85 13 43 10  2  3]
  [36 71 60 65 31 15]
  [ 4  4 73 90 20 72]]]


In [40]:
# arr4d = np.random.randint(1,100,(3,3,6,6))
# print(arr4d)

In [41]:
arrs3d = np.random.randint(1,100,(4,3,3))
print(arrs3d)

[[[41  4 13]
  [ 2 12 67]
  [38 55 68]]

 [[ 3 55 37]
  [40 92 96]
  [18 40 77]]

 [[31 86 30]
  [12 21 75]
  [33 73 18]]

 [[63 20 37]
  [37 33 15]
  [27 26 33]]]


In [42]:
#  press alt+shift+down arrow to copy the license
# [41, 20]
# [41, 20]
# [41, 20]

In [44]:
print(arrs3d[1, 1:, 1:])

[[92 96]
 [40 77]]


In [49]:
arr2 = np.random.randint(low=1, high=20, size=(4, 4))
print(arr2)

[[ 1  3  1 13]
 [ 9 16  8  2]
 [ 7  2 11  6]
 [ 4 13  7  6]]


In [62]:
print(arr2[[0,-1]])  # rows 1 to 3 and columns 2 to 4

[[ 1  3  1 13]
 [ 4 13  7  6]]


In [66]:
print(arr2[[0,-1]][:,[0,-1]])

[[ 1 13]
 [ 4  6]]


In [67]:
arrp = arr2[[0,-1]]
print(arrp)

[[ 1  3  1 13]
 [ 4 13  7  6]]


In [69]:
arrp[:,[0,-1]] #arrp[rows, columns]

array([[ 1, 13],
       [ 4,  6]], dtype=int32)

In [70]:
# NumPy attributes and methods

arrna = np.random.randint(1,100,(4,5))
print(arrna)

[[37 62  4 20 54]
 [68 83 38 99 98]
 [ 4 96 21 98 40]
 [10 74 82  4 35]]


In [74]:
print(arrna.shape)
print(arrna.ndim)
print(arrna.size)
print(arrna.min())
print(arrna.max())
print(arrna.sum())
print(arrna.sum(axis=0)) # column-wise sum
print(arrna.sum(axis=1)) # row-wise sum
print(arrna.argmax(axis=0)) # column-wise index of max value

(4, 5)
2
20
4
99
1027
[119 315 145 221 227]
[177 386 259 205]
[1 2 3 1 1]


In [76]:
print(arrna.reshape(2,10)) # reshaping the array
print(arrna.reshape(-1)) # change nd array to 1d array using reshaping

[[37 62  4 20 54 68 83 38 99 98]
 [ 4 96 21 98 40 10 74 82  4 35]]
[37 62  4 20 54 68 83 38 99 98  4 96 21 98 40 10 74 82  4 35]


In [ ]:
# concatenation in numpy
# we will perform few numpy exercises
# pandas